@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWhpbm1wem4wMDAwdDJ0MG5na3BzOGw4IiwiZW1haWwiOiJjb2JhLWVseXNpYUBnbWFpbC5jb20iLCJpYXQiOjE3NjIxNDQ5OTYsImV4cCI6MTc2MjIzMTM5Nn0.ZyA4GNGaJvvCi7diPBagsZrYgwn76YniSpfSg6lbGgI
@hostname = http://localhost:3000

@categoryId_Kind = cmhinrlra0004t2t0c68ae8mj
@categoryId_Type = cmhinrvcx0006t2t0unmxzoj6
@categoryId_Collect = cmhinpvnf0002t2t04oy1blv5
@categoryId_Update = cmhinrvcx0006t2t0unmxzoj6

POST {{hostname}}/tasks
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Selesaikan coding task routes (v2 - Many-to-Many)",
    "isCompleted": false,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Type}}",
        "{{categoryId_Collect}}"
    ]
}

###

GET {{hostname}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
@taskId = cmhintcox0008t2t086dxpnhm

GET {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}

###

PATCH {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Task routes v2 (DI-UPDATE)",
    "isCompleted": true,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Update}}", 
        "{{categoryId_Collect}}"
    ]
}

###

DELETE {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}

